/* LOGIN */
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

/* LOGOUT */
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

/* TOKEN */
export const GET_TOKEN = "GET_TOKEN";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

// ALBUM
export const GET_ALBUM = "GET_ALBUM";
export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS";
export const GET_ALBUM_FAILURE = "GET_ALBUM_FAILURE";
export const ADD_ALBUM= "ADD_ALBUM";
export const ADD_ALBUM_SUCCESS = "ADD_ALBUM_SUCCESS";
export const ADD_ALBUM_FAILURE = "ADD_ALBUM_FAILURE";
export const EDIT_ALBUM= "EDIT_ALBUM";
export const EDIT_ALBUM_SUCCESS = "EDIT_ALBUM_SUCCESS";
export const EDIT_ALBUM_FAILURE = "EDIT_ALBUM_FAILURE";
export const DELETE_ALBUM_SUCCESS = "DELETE_ALBUM_SUCCESS";
export const DELETE_ALBUM_FAILURE = "DELETE_ALBUM_FAILURE";

// PARTNER
export const GET_PARTNER = "GET_PARTNER";
export const GET_PARTNER_SUCCESS = "GET_PARTNER_SUCCESS";
export const GET_PARTNER_FAILURE = "GET_PARTNER_FAILURE";
export const ADD_PARTNER= "ADD_PARTNER";
export const ADD_PARTNER_SUCCESS = "ADD_PARTNER_SUCCESS";
export const ADD_PARTNER_FAILURE = "ADD_PARTNER_FAILURE";
export const EDIT_PARTNER= "EDIT_PARTNER";
export const EDIT_PARTNER_SUCCESS = "EDIT_PARTNER_SUCCESS";
export const EDIT_PARTNER_FAILURE = "EDIT_PARTNER_FAILURE";
export const DELETE_PARTNER_SUCCESS = "DELETE_PARTNER_SUCCESS";
export const DELETE_PARTNER_FAILURE = "DELETE_PARTNER_FAILURE";

// BANNER
export const GET_BANNER = "GET_BANNER";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAILURE = "GET_BANNER_FAILURE";
export const ADD_BANNER= "ADD_BANNER";
export const ADD_BANNER_SUCCESS = "ADD_BANNER_SUCCESS";
export const ADD_BANNER_FAILURE = "ADD_BANNER_FAILURE";
export const EDIT_BANNER= "EDIT_BANNER";
export const EDIT_BANNER_SUCCESS = "EDIT_BANNER_SUCCESS";
export const EDIT_BANNER_FAILURE = "EDIT_BANNER_FAILURE";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_FAILURE = "DELETE_BANNER_FAILURE";

// BERITA
export const GET_BERITA = "GET_BERITA";
export const GET_BERITA_SUCCESS = "GET_BERITA_SUCCESS";
export const GET_BERITA_FAILURE = "GET_BERITA_FAILURE";
export const GET_DETAIL_BERITA = "GET_DETAIL_BERITA";
export const GET_DETAIL_BERITA_SUCCESS = "GET_DETAIL_BERITA_SUCCESS";
export const GET_DETAIL_BERITA_FAILURE = "GET_DETAIL_BERITA_FAILURE";
export const ADD_BERITA= "ADD_BERITA";
export const ADD_BERITA_SUCCESS = "ADD_BERITA_SUCCESS";
export const ADD_BERITA_FAILURE = "ADD_BERITA_FAILURE";
export const EDIT_BERITA= "EDIT_BERITA";
export const EDIT_BERITA_SUCCESS = "EDIT_BERITA_SUCCESS";
export const EDIT_BERITA_FAILURE = "EDIT_BERITA_FAILURE";
export const DELETE_BERITA_SUCCESS = "DELETE_BERITA_SUCCESS";
export const DELETE_BERITA_FAILURE = "DELETE_BERITA_FAILURE";

// DONASI
export const GET_DONASI = "GET_DONASI";
export const GET_DONASI_SUCCESS = "GET_DONASI_SUCCESS";
export const GET_DONASI_FAILURE = "GET_DONASI_FAILURE";
export const ADD_DONASI= "ADD_DONASI";
export const ADD_DONASI_SUCCESS = "ADD_DONASI_SUCCESS";
export const ADD_DONASI_FAILURE = "ADD_DONASI_FAILURE";
export const EDIT_DONASI= "EDIT_DONASI";
export const EDIT_DONASI_SUCCESS = "EDIT_DONASI_SUCCESS";
export const EDIT_DONASI_FAILURE = "EDIT_DONASI_FAILURE";
export const DELETE_DONASI_SUCCESS = "DELETE_DONASI_SUCCESS";
export const DELETE_DONASI_FAILURE = "DELETE_DONASI_FAILURE";

// DONASI_RUTIN
export const GET_DONASI_RUTIN = "GET_DONASI_RUTIN";
export const GET_DONASI_RUTIN_SUCCESS = "GET_DONASI_RUTIN_SUCCESS";
export const GET_DONASI_RUTIN_FAILURE = "GET_DONASI_RUTIN_FAILURE";
export const ADD_DONASI_RUTIN= "ADD_DONASI_RUTIN";
export const ADD_DONASI_RUTIN_SUCCESS = "ADD_DONASI_RUTIN_SUCCESS";
export const ADD_DONASI_RUTIN_FAILURE = "ADD_DONASI_RUTIN_FAILURE";
export const EDIT_DONASI_RUTIN= "EDIT_DONASI_RUTIN";
export const EDIT_DONASI_RUTIN_SUCCESS = "EDIT_DONASI_RUTIN_SUCCESS";
export const EDIT_DONASI_RUTIN_FAILURE = "EDIT_DONASI_RUTIN_FAILURE";
export const DELETE_DONASI_RUTIN_SUCCESS = "DELETE_DONASI_RUTIN_SUCCESS";
export const DELETE_DONASI_RUTIN_FAILURE = "DELETE_DONASI_FAILURE";

// DONASI_KATEGORI
export const GET_DONASI_KATEGORI = "GET_DONASI_KATEGORI";
export const GET_DONASI_KATEGORI_SUCCESS = "GET_DONASI_KATEGORI_SUCCESS";
export const GET_DONASI_KATEGORI_FAILURE = "GET_DONASI_KATEGORI_FAILURE";
export const ADD_DONASI_KATEGORI= "ADD_DONASI_KATEGORI";
export const ADD_DONASI_KATEGORI_SUCCESS = "ADD_DONASI_KATEGORI_SUCCESS";
export const ADD_DONASI_KATEGORI_FAILURE = "ADD_DONASI_KATEGORI_FAILURE";
export const EDIT_DONASI_KATEGORI= "EDIT_DONASI_KATEGORI";
export const EDIT_DONASI_KATEGORI_SUCCESS = "EDIT_DONASI_KATEGORI_SUCCESS";
export const EDIT_DONASI_KATEGORI_FAILURE = "EDIT_DONASI_KATEGORI_FAILURE";
export const DELETE_DONASI_KATEGORI_SUCCESS = "DELETE_DONASI_KATEGORI_SUCCESS";
export const DELETE_DONASI_KATEGORI_FAILURE = "DELETE_DONASI_KATEGORI_FAILURE";

// PROGRAM
export const GET_PROGRAM = "GET_PROGRAM";
export const GET_PROGRAM_SUCCESS = "GET_PROGRAM_SUCCESS";
export const GET_PROGRAM_FAILURE = "GET_PROGRAM_FAILURE";
export const GET_DETAIL_PROGRAM = "GET_DETAIL_PROGRAM";
export const GET_DETAIL_PROGRAM_SUCCESS = "GET_DETAIL_PROGRAM_SUCCESS";
export const GET_DETAIL_PROGRAM_CONTENT = "GET_DETAIL_PROGRAM_CONTENT";
export const GET_DETAIL_PROGRAM_FAILURE = "GET_DETAIL_PROGRAM_FAILURE";
export const ADD_PROGRAM= "ADD_PROGRAM";
export const ADD_PROGRAM_SUCCESS = "ADD_PROGRAM_SUCCESS";
export const ADD_PROGRAM_FAILURE = "ADD_PROGRAM_FAILURE";
export const EDIT_PROGRAM= "EDIT_PROGRAM";
export const EDIT_PROGRAM_SUCCESS = "EDIT_PROGRAM_SUCCESS";
export const EDIT_PROGRAM_FAILURE = "EDIT_PROGRAM_FAILURE";
export const DELETE_PROGRAM_SUCCESS = "DELETE_PROGRAM_SUCCESS";
export const DELETE_PROGRAM_FAILURE = "DELETE_PROGRAM_FAILURE";

// TENTANG
export const GET_TENTANG = "GET_TENTANG";
export const GET_TENTANG_SUCCESS = "GET_TENTANG_SUCCESS";
export const GET_TENTANG_FAILURE = "GET_TENTANG_FAILURE";
export const ADD_TENTANG= "ADD_TENTANG";
export const ADD_TENTANG_SUCCESS = "ADD_TENTANG_SUCCESS";
export const ADD_TENTANG_FAILURE = "ADD_TENTANG_FAILURE";
export const EDIT_TENTANG= "EDIT_TENTANG";
export const EDIT_TENTANG_SUCCESS = "EDIT_TENTANG_SUCCESS";
export const EDIT_TENTANG_FAILURE = "EDIT_TENTANG_FAILURE";
export const DELETE_TENTANG_SUCCESS = "DELETE_TENTANG_SUCCESS";
export const DELETE_TENTANG_FAILURE = "DELETE_TENTANG_FAILURE";

// TEAM
export const GET_TEAM = "GET_TEAM";
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const GET_TEAM_FAILURE = "GET_TEAM_FAILURE";
export const ADD_TEAM= "ADD_TEAM";
export const ADD_TEAM_SUCCESS = "ADD_TEAM_SUCCESS";
export const ADD_TEAM_FAILURE = "ADD_TEAM_FAILURE";
export const EDIT_TEAM= "EDIT_TEAM";
export const EDIT_TEAM_SUCCESS = "EDIT_TEAM_SUCCESS";
export const EDIT_TEAM_FAILURE = "EDIT_TEAM_FAILURE";
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";
export const DELETE_TEAM_FAILURE = "DELETE_TEAM_FAILURE";

// TESTIMONI
export const GET_TESTIMONI = "GET_TESTIMONI";
export const GET_TESTIMONI_SUCCESS = "GET_TESTIMONI_SUCCESS";
export const GET_TESTIMONI_FAILURE = "GET_TESTIMONI_FAILURE";
export const ADD_TESTIMONI= "ADD_TESTIMONI";
export const ADD_TESTIMONI_SUCCESS = "ADD_TESTIMONI_SUCCESS";
export const ADD_TESTIMONI_FAILURE = "ADD_TESTIMONI_FAILURE";
export const EDIT_TESTIMONI= "EDIT_TESTIMONI";
export const EDIT_TESTIMONI_SUCCESS = "EDIT_TESTIMONI_SUCCESS";
export const EDIT_TESTIMONI_FAILURE = "EDIT_TESTIMONI_FAILURE";
export const DELETE_TESTIMONI_SUCCESS = "DELETE_TESTIMONI_SUCCESS";
export const DELETE_TESTIMONI_FAILURE = "DELETE_TESTIMONI_FAILURE";

// USER
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const ADD_USER= "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const EDIT_USER= "EDIT_USER";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

// ROLE
export const GET_ROLE = "GET_ROLE";
export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const GET_ROLE_FAILURE = "GET_ROLE_FAILURE";

// BENEFICARIES
export const GET_BENEFICARIES = "GET_BENEFICARIES";
export const GET_BENEFICARIES_SUCCESS = "GET_BENEFICARIES_SUCCESS";
export const GET_BENEFICARIES_FAILURE = "GET_BENEFICARIES_FAILURE";
export const ADD_BENEFICARIES= "ADD_BENEFICARIES";
export const ADD_BENEFICARIES_SUCCESS = "ADD_BENEFICARIES_SUCCESS";
export const ADD_BENEFICARIES_FAILURE = "ADD_BENEFICARIES_FAILURE";
export const EDIT_BENEFICARIES= "EDIT_BENEFICARIES";
export const EDIT_BENEFICARIES_SUCCESS = "EDIT_BENEFICARIES_SUCCESS";
export const EDIT_BENEFICARIES_FAILURE = "EDIT_BENEFICARIES_FAILURE";
export const DELETE_BENEFICARIES_SUCCESS = "DELETE_BENEFICARIES_SUCCESS";
export const DELETE_BENEFICARIES_FAILURE = "DELETE_BENEFICARIES_FAILURE";

// PROFILE
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";

export const ROLE_TYPE = "ROLE_TYPE";

// CHANGE PASSWORD
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

// RESET PASSWORD
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

// ACHIEVEMENT
export const GET_ACHIEVEMENT = "GET_ACHIEVEMENT";
export const GET_ACHIEVEMENT_SUCCESS = "GET_ACHIEVEMENT_SUCCESS";
export const GET_ACHIEVEMENT_FAILURE = "GET_ACHIEVEMENT_FAILURE";
export const GET_DETAIL_ACHIEVEMENT = "GET_DETAIL_ACHIEVEMENT";
export const GET_DETAIL_ACHIEVEMENT_SUCCESS = "GET_DETAIL_ACHIEVEMENT_SUCCESS";
export const GET_DETAIL_ACHIEVEMENT_FAILURE = "GET_DETAIL_ACHIEVEMENT_FAILURE";
export const ADD_ACHIEVEMENT= "ADD_ACHIEVEMENT";
export const ADD_ACHIEVEMENT_SUCCESS = "ADD_ACHIEVEMENT_SUCCESS";
export const ADD_ACHIEVEMENT_FAILURE = "ADD_ACHIEVEMENT_FAILURE";
export const EDIT_ACHIEVEMENT= "EDIT_ACHIEVEMENT";
export const EDIT_ACHIEVEMENT_SUCCESS = "EDIT_ACHIEVEMENT_SUCCESS";
export const EDIT_ACHIEVEMENT_FAILURE = "EDIT_ACHIEVEMENT_FAILURE";
export const DELETE_ACHIEVEMENT_SUCCESS = "DELETE_ACHIEVEMENT_SUCCESS";
export const DELETE_ACHIEVEMENT_FAILURE = "DELETE_ACHIEVEMENT_FAILURE";

// KONTAK
export const GET_KONTAK = "GET_KONTAK";
export const GET_KONTAK_SUCCESS = "GET_KONTAK_SUCCESS";
export const GET_KONTAK_FAILURE = "GET_KONTAK_FAILURE";
export const ADD_KONTAK= "ADD_KONTAK";
export const ADD_KONTAK_SUCCESS = "ADD_KONTAK_SUCCESS";
export const ADD_KONTAK_FAILURE = "ADD_KONTAK_FAILURE";
export const EDIT_KONTAK= "EDIT_KONTAK";
export const EDIT_KONTAK_SUCCESS = "EDIT_KONTAK_SUCCESS";
export const EDIT_KONTAK_FAILURE = "EDIT_KONTAK_FAILURE";
export const DELETE_KONTAK_SUCCESS = "DELETE_KONTAK_SUCCESS";
export const DELETE_KONTAK_FAILURE = "DELETE_KONTAK_FAILURE";

// MENU
export const GET_MENU = "GET_MENU";
export const GET_MENU_SUCCESS = "GET_MENU_SUCCESS";
export const GET_MENU_FAILURE = "GET_MENU_FAILURE";
export const ADD_MENU= "ADD_MENU";
export const ADD_MENU_SUCCESS = "ADD_MENU_SUCCESS";
export const ADD_MENU_FAILURE = "ADD_MENU_FAILURE";
export const EDIT_MENU= "EDIT_MENU";
export const EDIT_MENU_SUCCESS = "EDIT_MENU_SUCCESS";
export const EDIT_MENU_FAILURE = "EDIT_MENU_FAILURE";
export const DELETE_MENU_SUCCESS = "DELETE_MENU_SUCCESS";
export const DELETE_MENU_FAILURE = "DELETE_MENU_FAILURE";

// HUBUNGI
export const GET_HUBUNGI = "GET_HUBUNGI";
export const GET_HUBUNGI_SUCCESS = "GET_HUBUNGI_SUCCESS";
export const GET_HUBUNGI_FAILURE = "GET_HUBUNGI_FAILURE";
export const ADD_HUBUNGI= "ADD_HUBUNGI";
export const ADD_HUBUNGI_SUCCESS = "ADD_HUBUNGI_SUCCESS";
export const ADD_HUBUNGI_FAILURE = "ADD_HUBUNGI_FAILURE";
export const EDIT_HUBUNGI= "EDIT_HUBUNGI";
export const EDIT_HUBUNGI_SUCCESS = "EDIT_HUBUNGI_SUCCESS";
export const EDIT_HUBUNGI_FAILURE = "EDIT_HUBUNGI_FAILURE";
export const DELETE_HUBUNGI_SUCCESS = "DELETE_HUBUNGI_SUCCESS";
export const DELETE_HUBUNGI_FAILURE = "DELETE_HUBUNGI_FAILURE";

// QRIS
export const GET_QRIS = "GET_QRIS";
export const GET_QRIS_SUCCESS = "GET_QRIS_SUCCESS";
export const GET_QRIS_FAILURE = "GET_QRIS_FAILURE";
export const ADD_QRIS= "ADD_QRIS";
export const ADD_QRIS_SUCCESS = "ADD_QRIS_SUCCESS";
export const ADD_QRIS_FAILURE = "ADD_QRIS_FAILURE";
export const EDIT_QRIS= "EDIT_QRIS";
export const EDIT_QRIS_SUCCESS = "EDIT_QRIS_SUCCESS";
export const EDIT_QRIS_FAILURE = "EDIT_QRIS_FAILURE";
export const DELETE_QRIS_SUCCESS = "DELETE_QRIS_SUCCESS";
export const DELETE_QRIS_FAILURE = "DELETE_QRIS_FAILURE";

// QRIS
export const GET_HISTORY = "GET_HISTORY";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_FAILURE = "GET_HISTORY_FAILURE";

// TRANSACTION
export const GET_TRANSACTION = "GET_TRANSACTION";
export const GET_TRANSACTION_SUCCESS = "GET_TRANSACTION_SUCCESS";
export const GET_TRANSACTION_FAILURE = "GET_TRANSACTION_FAILURE";
export const EDIT_TRANSACTION= "EDIT_TRANSACTION";
export const EDIT_TRANSACTION_SUCCESS = "EDIT_TRANSACTION_SUCCESS";
export const EDIT_TRANSACTION_FAILURE = "EDIT_TRANSACTION_FAILURE";
export const DELETE_TRANSACTION= "DELETE_TRANSACTION";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAILURE = "DELETE_TRANSACTION_FAILURE";

// PENGGALANG
export const GET_PENGGALANG = "GET_PENGGALANG";
export const GET_PENGGALANG_SUCCESS = "GET_PENGGALANG_SUCCESS";
export const GET_PENGGALANG_FAILURE = "GET_PENGGALANG_FAILURE";
export const ADD_PENGGALANG= "ADD_PENGGALANG";
export const ADD_PENGGALANG_SUCCESS = "ADD_PENGGALANG_SUCCESS";
export const ADD_PENGGALANG_FAILURE = "ADD_PENGGALANG_FAILURE";
export const EDIT_PENGGALANG= "EDIT_PENGGALANG";
export const EDIT_PENGGALANG_SUCCESS = "EDIT_PENGGALANG_SUCCESS";
export const EDIT_PENGGALANG_FAILURE = "EDIT_PENGGALANG_FAILURE";
export const DELETE_PENGGALANG_SUCCESS = "DELETE_PENGGALANG_SUCCESS";
export const DELETE_PENGGALANG_FAILURE = "DELETE_PENGGALANG_FAILURE";

// NOMINAL
export const GET_NOMINAL = "GET_NOMINAL";
export const GET_NOMINAL_SUCCESS = "GET_NOMINAL_SUCCESS";
export const GET_NOMINAL_FAILURE = "GET_NOMINAL_FAILURE";
export const ADD_NOMINAL= "ADD_NOMINAL";
export const ADD_NOMINAL_SUCCESS = "ADD_NOMINAL_SUCCESS";
export const ADD_NOMINAL_FAILURE = "ADD_NOMINAL_FAILURE";
export const DELETE_NOMINAL_SUCCESS = "DELETE_NOMINAL_SUCCESS";
export const DELETE_NOMINAL_FAILURE = "DELETE_NOMINAL_FAILURE";