/* TODO APP*/
export const GET_TOKEN = "GET_TOKEN";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

// ALBUM
export const GET_ALBUM = "GET_ALBUM";
export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS";
export const GET_ALBUM_FAILURE = "GET_ALBUM_FAILURE";
export const ADD_ALBUM= "ADD_ALBUM";
export const ADD_ALBUM_SUCCESS = "ADD_ALBUM_SUCCESS";
export const ADD_ALBUM_FAILURE = "ADD_ALBUM_FAILURE";
export const EDIT_ALBUM= "EDIT_ALBUM";
export const EDIT_ALBUM_SUCCESS = "EDIT_ALBUM_SUCCESS";
export const EDIT_ALBUM_FAILURE = "EDIT_ALBUM_FAILURE";
export const DELETE_ALBUM_SUCCESS = "DELETE_ALBUM_SUCCESS";
export const DELETE_ALBUM_FAILURE = "DELETE_ALBUM_FAILURE";


